name: kharach_guru
description: A modern Flutter expense tracker application with localization.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this for localization
    sdk: flutter

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # UI & Charting
  fl_chart: ^0.64.0
  intl: 0.20.2 # Required for localization
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true # Enable localization generation