name: kharach_guru
description: A modern Flutter expense tracker application with localization.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  provider: ^6.1.1
  fl_chart: ^0.64.0
  intl: 0.20.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/